import { createThemeContract } from "@vanilla-extract/css";

export const semanticTokens = createThemeContract({
	color: {
		primary: {
			surface: null,
			surfaceHover: null,
			surfaceActive: null,
			text: null,
			border: null,
			weak: null,
		},
		secondary: {
			surface: null,
			surfaceHover: null,
			surfaceActive: null,
			text: null,
			border: null,
			weak: null,
		},
		success: {
			surface: null,
			surfaceHover: null,
			surfaceActive: null,
			text: null,
			border: null,
			weak: null,
		},
		warning: {
			surface: null,
			surfaceHover: null,
			surfaceActive: null,
			text: null,
			border: null,
			weak: null,
		},
		danger: {
			surface: null,
			surfaceHover: null,
			surfaceActive: null,
			text: null,
			border: null,
			weak: null,
		},
		neutral: {
			surface: null,
			surfaceHover: null,
			surfaceActive: null,
			text: null,
			border: null,
			weak: null,
		},
		surface: {
			background: null,
			backgroundElevated: null,
			outline: null,
			text: null,
			textMuted: null,
			divider: null,
		},
	},
	spacing: {
		none: null,
		xxxs: null,
		xxs: null,
		xs: null,
		sm: null,
		md: null,
		lg: null,
		xl: null,
		xxl: null,
		xxxl: null,
	},
	typography: {
		fontFamily: {
			sans: null,
			mono: null,
			crayon: null,
		},
		fontSize: {
			xsmall: null,
			small: null,
			medium: null,
			large: null,
			xlarge: null,
			"display-small": null,
			"display-medium": null,
			"display-large": null,
		},
		lineHeight: {
			xsmall: null,
			small: null,
			medium: null,
			large: null,
			xlarge: null,
			"display-small": null,
			"display-medium": null,
			"display-large": null,
		},
		fontWeight: {
			regular: null,
			medium: null,
			semibold: null,
			bold: null,
		},
	},
	radius: {
		none: null,
		small: null,
		medium: null,
		large: null,
		xlarge: null,
		full: null,
	},
	shadow: {
		none: null,
		xsmall: null,
		small: null,
		medium: null,
		large: null,
		xlarge: null,
		pixelBox: null,
		pixelBoxMargin: null,
	},
	component: {
		button: {
			padding: {
				small: null,
				medium: null,
				large: null,
				xlarge: null,
			},
			radius: {
				small: null,
				medium: null,
				large: null,
			},
		},
		card: {
			radius: null,
			padding: null,
		},
		input: {
			radius: null,
			padding: null,
		},
	},
});

export const themeContract = semanticTokens;
